In [74]:
import tensorflow as tf

In [75]:
a = tf.Variable(tf.ones(shape=(1,3), dtype=tf.int32))
a

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[1, 1, 1]], dtype=int32)>

In [79]:
b = tf.constant(2)
x2_op = lambda a:a * b

In [81]:
r1 = x2_op(a * [1, 2, 3])
r2 = x2_op(a * [10, 20, 30])
tf.print(r1[0])
tf.print(r2[0])

[2 4 6]
[20 40 60]


In [82]:
print("Output:\n[2 4 6]\n[20 40 20]")

Output:
[2 4 6]
[20 40 20]
